[package]
name = "pgp"
version = "0.1.0"
authors = ["dignifiedquire <dignifiedquire@gmail.com>"]
description = "PGP implementation in Rust"
license = "MIT OR Apache-2.0"
homepage = "https://github.com/dignifiedquire/pgp"
repository = "https://github.com/dignifiedquire/pgp"

keywords = ["pgp", "gpg", "pretty good privacy", "email", "encryption", "privacy"]

[dependencies]
openssl = "^0.10"
crc24 = "^0.1"
base64 = "^0.9"
byteorder = "^1.1"
enum_primitive = "^0.1"
chrono = "^0.4"
failure = "^0.1"
circular = "^0.2"
itertools = "^0.7"
[dependencies.nom]
version = "^4.0"

[dev-dependencies]
hex-literal = "0.1"
hex = "0.3.2"
serde = "1.0.70"
serde_json = "1.0.22"

