[package]
name = "pgp"
version = "0.1.0"
authors = ["dignifiedquire <dignifiedquire@gmail.com>"]
description = "PGP implementation in Rust"
license = "MIT OR Apache-2.0"
homepage = "https://github.com/dignifiedquire/pgp"
repository = "https://github.com/dignifiedquire/pgp"

keywords = ["pgp", "gpg", "pretty good privacy", "email", "encryption", "privacy"]

[dependencies]
openssl = "^0.10"
crc24 = "^0.1"
base64 = "^0.9"
byteorder = "^1.2"
enum_primitive = "^0.1"
chrono = "^0.4"
failure = "^0.1"
circular = "^0.2"
itertools = "^0.7"
sha-1 = "^0.8"
sha2 = "^0.8"
md-5 = "^0.8"
ripemd160 = "^0.8"
generic-array = "^0.9"
digest = "^0.8"
aes = "^0.2"
blowfish = "^0.3"
twofish = "^0.1"
des = "^0.1"
block-modes = "^0.1"
hex = "^0.3"
cfb-mode = "^0.1"

[dependencies.nom]
version = "^4.0"

[dev-dependencies]
hex-literal = "^0.1"
serde = "^1.0"
serde_derive = "^1.0"
serde_json = "^1.0"
glob = "^0.2"
